// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: api/rpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EtcdxService_Get_FullMethodName = "/apipb.EtcdxService/Get"
	EtcdxService_Put_FullMethodName = "/apipb.EtcdxService/Put"
)

// EtcdxServiceClient is the client API for EtcdxService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EtcdxServiceClient interface {
	Get(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*RangeResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
}

type etcdxServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEtcdxServiceClient(cc grpc.ClientConnInterface) EtcdxServiceClient {
	return &etcdxServiceClient{cc}
}

func (c *etcdxServiceClient) Get(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (*RangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RangeResponse)
	err := c.cc.Invoke(ctx, EtcdxService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdxServiceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, EtcdxService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EtcdxServiceServer is the server API for EtcdxService service.
// All implementations must embed UnimplementedEtcdxServiceServer
// for forward compatibility.
type EtcdxServiceServer interface {
	Get(context.Context, *RangeRequest) (*RangeResponse, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	mustEmbedUnimplementedEtcdxServiceServer()
}

// UnimplementedEtcdxServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEtcdxServiceServer struct{}

func (UnimplementedEtcdxServiceServer) Get(context.Context, *RangeRequest) (*RangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedEtcdxServiceServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedEtcdxServiceServer) mustEmbedUnimplementedEtcdxServiceServer() {}
func (UnimplementedEtcdxServiceServer) testEmbeddedByValue()                      {}

// UnsafeEtcdxServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EtcdxServiceServer will
// result in compilation errors.
type UnsafeEtcdxServiceServer interface {
	mustEmbedUnimplementedEtcdxServiceServer()
}

func RegisterEtcdxServiceServer(s grpc.ServiceRegistrar, srv EtcdxServiceServer) {
	// If the following call pancis, it indicates UnimplementedEtcdxServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EtcdxService_ServiceDesc, srv)
}

func _EtcdxService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdxServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EtcdxService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdxServiceServer).Get(ctx, req.(*RangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EtcdxService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdxServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EtcdxService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdxServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EtcdxService_ServiceDesc is the grpc.ServiceDesc for EtcdxService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EtcdxService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apipb.EtcdxService",
	HandlerType: (*EtcdxServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _EtcdxService_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _EtcdxService_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rpc.proto",
}
